/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto_examen;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Arena extends javax.swing.JFrame {

    /**
     * Creates new form Arena
     */
 
    
    public Arena() {
        initComponents();
        figPiedra.setVisible(false);
        Armadillo1.setVisible(false);
        Dragon.setVisible(false);
        Safari.setVisible(false);
        Arce.setVisible(false);
        Tortuga.setVisible(false);
        //--------------------------------
        lbluno.setVisible(false);
        lbldos.setVisible(false);
        lbltres.setVisible(false);
        lblcuatro.setVisible(false);
        lblcinco.setVisible(false);
        lblseis.setVisible(false);
        lblvida1.setVisible(false);
        lblvida2.setVisible(false);
        lblpts1.setVisible(false);
        lblpts2.setVisible(false);
        //--------------------------------
        txtuno.setVisible(false);
        txtdos.setVisible(false);
        txttres.setVisible(false);
        txtcuatro.setVisible(false);
        txtcinco.setVisible(false);
        txtseis.setVisible(false);
        txtvida1.setVisible(false);
        txtvida2.setVisible(false);
        //--------------------------------
        btnuno.setVisible(false);
        btndos.setVisible(false);
        btntres.setVisible(false);
        btncuatro.setVisible(false);
        btncinco.setVisible(false);
        btnseis.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSelecc1 = new javax.swing.JComboBox();
        cmbSelecc2 = new javax.swing.JComboBox();
        Armadillo1 = new javax.swing.JLabel();
        figPiedra = new javax.swing.JLabel();
        Safari = new javax.swing.JLabel();
        Dragon = new javax.swing.JLabel();
        txtcuatro = new javax.swing.JTextField();
        lblcuatro = new javax.swing.JLabel();
        lblcinco = new javax.swing.JLabel();
        txtcinco = new javax.swing.JTextField();
        lblseis = new javax.swing.JLabel();
        txtseis = new javax.swing.JTextField();
        lbldos = new javax.swing.JLabel();
        lbluno = new javax.swing.JLabel();
        lbltres = new javax.swing.JLabel();
        txtuno = new javax.swing.JTextField();
        txtdos = new javax.swing.JTextField();
        txttres = new javax.swing.JTextField();
        btncuatro = new javax.swing.JButton();
        btncinco = new javax.swing.JButton();
        btnseis = new javax.swing.JButton();
        btntres = new javax.swing.JButton();
        btndos = new javax.swing.JButton();
        btnuno = new javax.swing.JButton();
        lblvida1 = new javax.swing.JLabel();
        txtvida1 = new javax.swing.JTextField();
        lblvida2 = new javax.swing.JLabel();
        txtvida2 = new javax.swing.JTextField();
        btnAbandonar = new javax.swing.JButton();
        Arce = new javax.swing.JLabel();
        Tortuga = new javax.swing.JLabel();
        lblpts1 = new javax.swing.JLabel();
        lblpts2 = new javax.swing.JLabel();
        btnEmpezar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbSelecc1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opción...", "Dragon", "Safari", "Arce" }));
        cmbSelecc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelecc1ActionPerformed(evt);
            }
        });

        cmbSelecc2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una Opción...", "Gusano de Piedra", "Armadillo", "Tortuga" }));
        cmbSelecc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelecc2ActionPerformed(evt);
            }
        });

        Armadillo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Proyecto_Examen\\Assets\\Armadillo1.png")); // NOI18N

        figPiedra.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Proyecto_Examen\\Assets\\Gusano1.png")); // NOI18N
        figPiedra.setToolTipText("");
        figPiedra.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_examen/Gusano1.png"))); // NOI18N

        Safari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_examen/Safari1.png"))); // NOI18N

        Dragon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_examen/Dragon1.png"))); // NOI18N

        txtcuatro.setEditable(false);
        txtcuatro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcuatro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtcuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcuatroActionPerformed(evt);
            }
        });

        lblcuatro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcuatro.setText("Ataque de Piedras:");

        lblcinco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcinco.setText("Bola Destructora:");

        txtcinco.setEditable(false);
        txtcinco.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcinco.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblseis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblseis.setText("Ataque Hoja Afilada:");

        txtseis.setEditable(false);
        txtseis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtseis.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lbldos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbldos.setText("Ataque de Energía:");

        lbluno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbluno.setText("Ataque de Fuego:");

        lbltres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbltres.setText("Ataque Relampago:");

        txtuno.setEditable(false);
        txtuno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtuno.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtunoActionPerformed(evt);
            }
        });

        txtdos.setEditable(false);
        txtdos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtdos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdosActionPerformed(evt);
            }
        });

        txttres.setEditable(false);
        txttres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttresActionPerformed(evt);
            }
        });

        btncuatro.setText("Atacar");
        btncuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuatroActionPerformed(evt);
            }
        });

        btncinco.setText("Atacar");
        btncinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncincoActionPerformed(evt);
            }
        });

        btnseis.setText("Atacar");
        btnseis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseisActionPerformed(evt);
            }
        });

        btntres.setText("Atacar");
        btntres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntresActionPerformed(evt);
            }
        });

        btndos.setText("Atacar");
        btndos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndosActionPerformed(evt);
            }
        });

        btnuno.setText("Atacar");
        btnuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnunoActionPerformed(evt);
            }
        });

        lblvida1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblvida1.setText("Vida: ");

        txtvida1.setEditable(false);
        txtvida1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvida1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvida1ActionPerformed(evt);
            }
        });

        lblvida2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblvida2.setText("Vida: ");

        txtvida2.setEditable(false);
        txtvida2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtvida2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvida2ActionPerformed(evt);
            }
        });

        btnAbandonar.setText("Cambiar Jugadores");
        btnAbandonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbandonarActionPerformed(evt);
            }
        });

        Arce.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Proyecto_Examen\\Assets\\Arce1.png")); // NOI18N

        Tortuga.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\Proyecto_Examen\\Assets\\Tortuga1.png")); // NOI18N

        lblpts1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpts1.setText("Pts.");

        lblpts2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblpts2.setText("Pts.");

        btnEmpezar.setText("Empezar");
        btnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpezarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Safari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Dragon, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Arce, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(cmbSelecc1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbldos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtdos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbluno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtuno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbltres, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(txttres, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btntres)
                                    .addComponent(btndos)
                                    .addComponent(btnuno))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Tortuga, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Armadillo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(figPiedra)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btncuatro))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblcinco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblseis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtseis, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnseis))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btncinco)))))
                            .addGap(29, 29, 29))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblvida2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtvida2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblpts2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(92, 92, 92)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmbSelecc2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblvida1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtvida1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblpts1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(654, 654, 654))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(btnAbandonar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(btnEmpezar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnEmpezar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSelecc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSelecc1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(figPiedra)
                            .addComponent(Safari, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Arce, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Dragon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tortuga, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Armadillo1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcuatro)
                            .addComponent(txtcuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncuatro))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcinco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcinco, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncinco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblseis)
                            .addComponent(txtseis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnseis)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuno, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbluno, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnuno))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldos, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndos))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbltres, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntres))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvida1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvida1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblvida2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvida2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpts1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpts2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbandonar)
                    .addComponent(btnSalir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelecc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelecc1ActionPerformed
        // TODO add your handling code here:
        
        int quest1 = cmbSelecc1.getSelectedIndex();
        
        if (quest1 == 1 || quest1 == 2 || quest1 == 3) {
            lbluno.setVisible(true); lbldos.setVisible(true); lbltres.setVisible(true); lblvida1.setVisible(true); lblpts1.setVisible(true);
            txtuno.setVisible(true); txtdos.setVisible(true); txttres.setVisible(true); txtvida1.setVisible(true);
            //btnuno.setVisible(false); btndos.setVisible(false); btntres.setVisible(true);

            txtuno.setText(String.valueOf(3));
            int ataque1 = Integer.parseInt(txtuno.getText());
            ataque1 += 3 +(Math.random()* 6)%2;
            txtuno.setText(""+ataque1);

            txtdos.setText(String.valueOf(2));
            int ataque2 = Integer.parseInt(txtdos.getText());
            ataque2 += 2 +(Math.random()* 4)%2;
            txtdos.setText(""+ataque2);

            txttres.setText(String.valueOf(1));
            int ataque3 = Integer.parseInt(txttres.getText());
            ataque3 += 1 +(Math.random()* 2)%2;
            txttres.setText(""+ataque3);

            txtvida1.setText(String.valueOf(1));
            int vida1 = Integer.parseInt(txtvida1.getText());
            vida1 += 98 +(Math.random()* 400)%4;
            txtvida1.setText(""+vida1);
        }
        
        if (quest1 == 1) {
            Dragon.setVisible(true);
            cmbSelecc1.setEnabled(false);
        }
        
        if (quest1 == 2) {
            Safari.setVisible(true);
            cmbSelecc1.setEnabled(false);
        }
        
        if (quest1 == 3) {
            Arce.setVisible(true);
            cmbSelecc1.setEnabled(false);
        }
    }//GEN-LAST:event_cmbSelecc1ActionPerformed

    private void cmbSelecc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelecc2ActionPerformed
        // TODO add your handling code here:
     
        int quest2 = cmbSelecc2.getSelectedIndex();
        
        if (quest2 == 1 || quest2 == 2 || quest2 == 3) {
            lblcuatro.setVisible(true); lblcinco.setVisible(true); lblseis.setVisible(true); lblvida2.setVisible(true); lblpts2.setVisible(true);
            txtcuatro.setVisible(true); txtcinco.setVisible(true); txtseis.setVisible(true); txtvida2.setVisible(true);
            //btncuatro.setVisible(true); btncinco.setVisible(true); btnseis.setVisible(true);

            txtcuatro.setText(String.valueOf(2));
            int ataque4 = Integer.parseInt(txtcuatro.getText());
            ataque4 += 5 +(Math.random()* 6)%2;
            txtcuatro.setText(""+ataque4);

            txtcinco.setText(String.valueOf(4));
            int ataque5 = Integer.parseInt(txtcinco.getText());
            ataque5 += 3 +(Math.random()* 6)%2;
            txtcinco.setText(""+ataque5);

            txtseis.setText(String.valueOf(0));
            int ataque6 = Integer.parseInt(txtseis.getText());
            ataque6 += 2 +(Math.random()* 6)%2;
            txtseis.setText(""+ataque6);

            txtvida2.setText(String.valueOf(1));
            int vida2 = Integer.parseInt(txtvida2.getText());
            vida2 += 99 +(Math.random()* 397)%4;
            txtvida2.setText(""+vida2);
        }
        
        if (quest2 == 1) {
            figPiedra.setVisible(true);
            cmbSelecc2.setEnabled(false);
        }
        
        if (quest2 == 2) {
            Armadillo1.setVisible(true);
            cmbSelecc2.setEnabled(false);
        }
        
        if (quest2 == 3) {
            Tortuga.setVisible(true);
            cmbSelecc2.setEnabled(false);
        }
    }//GEN-LAST:event_cmbSelecc2ActionPerformed

    private void txtcuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcuatroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcuatroActionPerformed

    private void txtunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtunoActionPerformed

    private void txtdosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdosActionPerformed

    private void txttresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttresActionPerformed

    private void txtvida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvida1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvida1ActionPerformed

    private void txtvida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvida2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvida2ActionPerformed

    private void btnAbandonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbandonarActionPerformed
        // TODO add your handling code here:
        figPiedra.setVisible(false);
        Armadillo1.setVisible(false);
        Dragon.setVisible(false);
        Safari.setVisible(false);
        Arce.setVisible(false);
        Tortuga.setVisible(false);
        //--------------------------------
        lbluno.setVisible(false);
        lbldos.setVisible(false);
        lbltres.setVisible(false);
        lblcuatro.setVisible(false);
        lblcinco.setVisible(false);
        lblseis.setVisible(false);
        lblvida1.setVisible(false);
        lblvida2.setVisible(false);
        lblpts1.setVisible(false);
        lblpts2.setVisible(false);
        //--------------------------------
        txtuno.setVisible(false);
        txtdos.setVisible(false);
        txttres.setVisible(false);
        txtcuatro.setVisible(false);
        txtcinco.setVisible(false);
        txtseis.setVisible(false);
        txtvida1.setVisible(false);
        txtvida2.setVisible(false);
        //--------------------------------
        btnuno.setVisible(false);
        btndos.setVisible(false);
        btntres.setVisible(false);
        btncuatro.setVisible(false);
        btncinco.setVisible(false);
        btnseis.setVisible(false);
        //-------------------------------
        cmbSelecc1.setEnabled(true);
        cmbSelecc2.setEnabled(true);   
        //-------------------------------
        cmbSelecc2.setSelectedIndex(0);
        cmbSelecc1.setSelectedIndex(0);
    }//GEN-LAST:event_btnAbandonarActionPerformed

    private void btnunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnunoActionPerformed
        // TODO add your handling code here:
        //btnAbandonar.setVisible(false);
        //turno1();
        msjVida1();
        turno2();
        int txt4 = Integer.parseInt(txtvida2.getText());
        txt4 -= 1 +(Math.random()*3)%4;
        txtvida2.setText(""+txt4);

        int baja1 = Integer.parseInt(txtuno.getText());
        baja1 -= 1;
        txtuno.setText(""+baja1); 
        
        if (baja1 == 0) {
            btnuno.setVisible(false);
        } 
        
    }//GEN-LAST:event_btnunoActionPerformed

    private void btndosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndosActionPerformed
        // TODO add your handling code here:
        //btnAbandonar.setVisible(false);
        msjVida1();
        turno2();
        int txt5 = Integer.parseInt(txtvida2.getText());
        txt5 -= 2 +(Math.random()*3)%4;
        txtvida2.setText(""+txt5);

        int baja2 = Integer.parseInt(txtdos.getText());
        baja2 -= 1;
        txtdos.setText(""+baja2);

        if (baja2 == 0) {
            btndos.setVisible(false);
        } 
        
    }//GEN-LAST:event_btndosActionPerformed

    private void btntresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntresActionPerformed
        // TODO add your handling code here:
        //btnAbandonar.setVisible(false);
        msjVida1();
        turno2();
        int txt6 = Integer.parseInt(txtvida2.getText());
        txt6 -= 20 +(Math.random()*3)%4;///modificar
        txtvida2.setText(""+txt6);

        int baja3 = Integer.parseInt(txttres.getText());
        baja3 -= 1;
        txttres.setText(""+baja3);

        if (baja3 == 0) {
            btntres.setVisible(false);
        } 
        
    }//GEN-LAST:event_btntresActionPerformed

    private void btnseisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseisActionPerformed
        // TODO add your handling code here:
        //btnAbandonar.setVisible(false);
        msjVida2();
        turno1();
        int txt3 = Integer.parseInt(txtvida1.getText());
        txt3 -= 15 +(Math.random()*3)%4;
        txtvida1.setText(""+txt3);

        int baja6 = Integer.parseInt(txtseis.getText());
        baja6 -= 1;
        txtseis.setText(""+baja6);

        if (baja6 == 0) {
            btnseis.setVisible(false);
        } 
    }//GEN-LAST:event_btnseisActionPerformed

    private void btncincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncincoActionPerformed
        // TODO add your handling code here:
        //btnAbandonar.setVisible(false);
        msjVida2();
        turno1();
        int txt2 = Integer.parseInt(txtvida1.getText());
        txt2 -= 3 +(Math.random()*5)%4;
        txtvida1.setText(""+txt2);
        
        int baja5 = Integer.parseInt(txtcinco.getText());
        baja5 -= 1;
        txtcinco.setText(""+baja5);
        
        if (baja5 ==0) {
            btncinco.setVisible(false);
        }
    }//GEN-LAST:event_btncincoActionPerformed

    private void btncuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuatroActionPerformed
        // TODO add your handling code here:
        msjVida2();
        turno1();
        int txt1 = Integer.parseInt(txtvida1.getText());
        txt1 -= 2 +(Math.random()*15)%10;
        txtvida1.setText(""+txt1);
        
        int baja4 = Integer.parseInt(txtcuatro.getText());
        baja4 -= 1;
        txtcuatro.setText(""+baja4);
        
        if (baja4 == 0) {
            btncuatro.setVisible(false);
        }
    }//GEN-LAST:event_btncuatroActionPerformed

    private void btnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpezarActionPerformed
        // TODO add your handling code here:
        int quest2 = cmbSelecc2.getSelectedIndex();
        int quest1 = cmbSelecc1.getSelectedIndex();
        
        if (quest1 != 0 && quest2 != 0) {
            btnuno.setVisible(true); btndos.setVisible(true); btntres.setVisible(true);
            btncuatro.setVisible(true); btncinco.setVisible(true); btnseis.setVisible(true);

            btnAbandonar.setEnabled(false);

            btnEmpezar.setText("Jugando");
            btnEmpezar.setEnabled(false);
        }
    }//GEN-LAST:event_btnEmpezarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void turno1(){
        btnuno.setEnabled(true);
        btndos.setEnabled(true);
        btntres.setEnabled(true);
        btncuatro.setEnabled(false);
        btncinco.setEnabled(false);
        btnseis.setEnabled(false);
    }
    
    public void turno2(){
        btnuno.setEnabled(false);
        btndos.setEnabled(false);
        btntres.setEnabled(false);
        btncuatro.setEnabled(true);
        btncinco.setEnabled(true);
        btnseis.setEnabled(true);
    }
    
    public void msjVida1(){
        int caja1 = Integer.parseInt(txtuno.getText());
        int caja2 = Integer.parseInt(txtdos.getText());
        int caja3 = Integer.parseInt(txttres.getText());
        int vencido1 = Integer.parseInt(txtvida1.getText());
        int vencido2 = Integer.parseInt(txtvida2.getText());
        if (caja1 <= 0 && caja2 <= 0 && caja3 <= 0 || vencido1 <= 0 && vencido1 < vencido2) {
            JOptionPane.showMessageDialog(txtvida1, "Dragon, Safari y Arce\n\t\t------HAN PERDIDO------");
        }
    }
    
    public void msjVida2(){
        int caja4 = Integer.parseInt(txtcuatro.getText());
        int caja5 = Integer.parseInt(txtcinco.getText());
        int caja6 = Integer.parseInt(txtseis.getText());
        int vencido1 = Integer.parseInt(txtvida1.getText());
        int vencido2 = Integer.parseInt(txtvida2.getText());
        if (caja4 <= 0 && caja5 <= 0 && caja6 <= 0 || vencido2 <= 0 && vencido2 < vencido1) {
            JOptionPane.showMessageDialog(txtvida1, "Gusano de Piedra, Armadillo y Tortuga\n\t\t------HAN PERDIDO------");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Arce;
    private javax.swing.JLabel Armadillo1;
    private javax.swing.JLabel Dragon;
    private javax.swing.JLabel Safari;
    private javax.swing.JLabel Tortuga;
    private javax.swing.JButton btnAbandonar;
    private javax.swing.JButton btnEmpezar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btncinco;
    private javax.swing.JButton btncuatro;
    private javax.swing.JButton btndos;
    private javax.swing.JButton btnseis;
    private javax.swing.JButton btntres;
    private javax.swing.JButton btnuno;
    private javax.swing.JComboBox cmbSelecc1;
    private javax.swing.JComboBox cmbSelecc2;
    private javax.swing.JLabel figPiedra;
    private javax.swing.JLabel lblcinco;
    private javax.swing.JLabel lblcuatro;
    private javax.swing.JLabel lbldos;
    private javax.swing.JLabel lblpts1;
    private javax.swing.JLabel lblpts2;
    private javax.swing.JLabel lblseis;
    private javax.swing.JLabel lbltres;
    private javax.swing.JLabel lbluno;
    private javax.swing.JLabel lblvida1;
    private javax.swing.JLabel lblvida2;
    private javax.swing.JTextField txtcinco;
    private javax.swing.JTextField txtcuatro;
    private javax.swing.JTextField txtdos;
    private javax.swing.JTextField txtseis;
    private javax.swing.JTextField txttres;
    private javax.swing.JTextField txtuno;
    private javax.swing.JTextField txtvida1;
    private javax.swing.JTextField txtvida2;
    // End of variables declaration//GEN-END:variables
}
